### ISSUE TITLE
alpine image needs groupmod and usermod

### ISSUE THREAD

**Issue by clux** [lalbuild/dockerfiles#1]
Found another dependency on docker images that I didn't know about:

```sh
/bin/sh: groupmod: not found
The command '/bin/sh -c groupmod -g 2000 lal && usermod -u 2000 lal' returned a non-zero code: 127
thread 'main' panicked at 'shell echoed', tests/testmain.rs:234:4
```

travis has uid 2000 and run into this using the alpine image in tests, so it will try to modify the group and user id of the lal user by using `groupmod` and `usermod`. These need to exist inside the containers.

**Comment by clux** [comment]
Fixed in https://github.com/lalbuild/dockerfiles/commit/e7d62f62fe250ac735096adfdc7cc34184b73c77 

New alpine image pushed just now.

**Comment by clux** [comment]
However, this does not fix the alpine image..

```sh
lal::shell: Using container clux/lal-alpine-u2000_g2000:from_f8cc00c74f06
lal::shell: Attempting to build container clux/lal-alpine-u2000_g2000:from_f8cc00c74f06...
Sending build context to Docker daemon 2.048 kB
Step 1/4 : FROM clux/lal-alpine:3.6
 ---> f8cc00c74f06
Step 2/4 : USER root
 ---> Running in 0249a89bb2fe
 ---> 37f1fbf57d62
Removing intermediate container 0249a89bb2fe
Step 3/4 : RUN groupmod -g 2000 lal && usermod -u 2000 lal
 ---> Running in 29da84d35592
groupmod: group 'lal' does not exist
The command '/bin/sh -c groupmod -g 2000 lal && usermod -u 2000 lal' returned a non-zero code: 6
thread 'main' panicked at 'shell echoed', tests/testmain.rs:234:4
```

because the alpine image does not have a `lal` group..

**Comment by clux** [comment]
Fixed now.
